FROM ubuntu

#Install git
RUN apt-get update && \
     apt-get install -y git python3.7 python3-pip python3-venv mongodb-server

# RUN pip3 install virtualenv

RUN mkdir -p /home/ivado/ivado_task && \      
           cd /home/ivado \
           git clone https://github.com/amrnablus/ivado_task.git



RUN cd /home/ivado/ivado_task && \
     pip install -r requirements.txt

RUN cd /home/ivado/ivado_task && \
     scrapy crawl musmuems

RUN cd /home/ivado/ivado_task && \
     scrapy crawl musmuems

RUN cd /home/ivado/ivado_task && \
     PYTHONPATH=$PYTHONPATH:`pwd` python extra_data/city_population.py


RUN cd /home/ivado/ivado_task && \
     PYTHONPATH=$PYTHONPATH:`pwd` python ml/linear_regression_influx_pred.py

#Set working directory
WORKDIR /home/ivado


